pub const BRIDGE_NOT_INITIALIZED: felt252 = 'BRIDGE_NOT_INITIALIZED';
pub const BRIDGE_ALREADY_INITIALIZED: felt252 = 'BRIDGE_ALREADY_INITIALIZED';
pub const DUP_PUBLIC_KEY: felt252 = 'DUP_PUBLIC_KEY';
pub const INVALID_QUORUM: felt252 = 'INVALID_QUORUM';
pub const INVALID_WITHDRAW_AMOUNT: felt252 = 'INVALID_WITHDRAW_AMOUNT';
pub const ONLY_SIGNER: felt252 = 'ONLY_SIGNER';
pub const ONLY_USER: felt252 = 'ONLY_USER';
pub const SIGNER_BLACKLISTED: felt252 = 'SIGNER_BLACKLISTED';
pub const SIGNER_NOT_REGISTERED: felt252 = 'SIGNER_NOT_REGISTERED';
pub const USER_ALREADY_REGISTERED: felt252 = 'USER_ALREADY_REGISTERED';
pub const USER_NOT_REGISTERED: felt252 = 'USER_NOT_REGISTERED';
pub const ZERO_BTC_DESTINATION: felt252 = 'ZERO_BTC_DESTINATION';
pub const ZERO_PUBLIC_KEY: felt252 = 'ZERO_PUBLIC_KEY';
pub const ZERO_REGISTRY_ADDRESS: felt252 = 'ZERO_REGISTRY_ADDRESS';
pub const ZERO_SIGNER: felt252 = 'ZERO_SIGNER';
pub const ZERO_TOKEN_ADDRESS: felt252 = 'ZERO_TOKEN_ADDRESS';
pub const ZERO_USER: felt252 = 'ZERO_USER';

