[workspace]
members = ["registry", "token", "bridge"]

[workspace.package]
version = "0.1.0"
edition = "2024_07"

[workspace.dependencies]
starknet = "2.15.1"
assert_macros = "2.15.1"
openzeppelin = "3.0.0"
snforge_std = "0.55.0"
starkware_utils = { git = "https://github.com/starkware-libs/starkware-starknet-utils", rev = "0a48bdf01c39ccd41d797c6049cf9ab5075bca45" }
starkware_utils_testing = { git = "https://github.com/starkware-libs/starkware-starknet-utils", rev = "0a48bdf01c39ccd41d797c6049cf9ab5075bca45" }

[scripts]
test = "snforge test"

[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"

[workspace.tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
